preserve_hierarchy: false
files:
  - source: composeApp/src/commonMain/moko-resources/base/strings.xml
    translation: /%locale%/strings.xml
    update_option: update_as_unapproved
    ignore:
      - /images/
      - /fonts/

  - source: composeApp/src/commonMain/moko-resources/base/plurals.xml
    translation: /%locale%/plurals.xml
    update_option: update_as_unapproved
    ignore:
      - /images/
      - /fonts/