base_path: composeApp/src/commonMain/moko-resources
preserve_hierarchy: true
files:
  - source: /base/strings.xml
    translation: /%locale%/strings.xml
    update_option: update_as_unapproved
    ignore:
      - /images/
      - /fonts/

  - source: /base/plurals.xml
    translation: /%locale%/plurals.xml
    update_option: update_as_unapproved
    ignore:
      - /images/
      - /fonts/